/**
 * Language switcher functionality for Affiliate Finder
 * Supports English and Vietnamese localization
 */

// Translation dictionary
const translations = {
  // English translations
  en: {
    // General UI elements
    backButton: "Back to Programs",
    programName: "Binance Affiliate Program",
    category: "Cryptocurrency Exchange",
    joinButton: "Join Program",
    saveButton: "Save",
    shareButton: "Share",
    description: "Binance's Affiliate Program allows you to earn up to 50% commission on trading fees from your referrals. As the world's largest cryptocurrency exchange by volume, Binance offers a trusted platform with extensive marketing tools and timely payments.",
    
    // Statistics and metrics
    commissionRate: "Commission Rate",
    commissionDetail: "Lifetime commission on trading fees",
    cookieDuration: "Cookie Duration",
    cookieDetail: "Plus permanent tracking for registered users",
    monthlyTraffic: "Monthly Traffic",
    trafficDetail: "Global visitors (last 30 days)",
    paymentFrequency: "Payment Frequency",
    paymentValue: "Daily to Monthly",
    paymentDetail: "Customizable payment schedule",
    
    // Program details
    programDetails: "Program Details",
    detailsContent1: "The Binance Affiliate Program offers one of the industry's most competitive commission structures. Affiliates can earn up to 50% of the trading fees generated by referred users. The earnings are calculated based on the trading volume of your referrals and are available through a customizable payment schedule.",
    detailsContent2: "Binance provides dedicated account managers to help optimize your campaigns and maximize conversions. The platform offers real-time reporting, detailed analytics, and a comprehensive set of marketing materials to support your promotional efforts.",
    keyFeatures: "Key Features",
    feature1: "Up to 50% commission on trading fees",
    feature2: "Real-time reporting and analytics",
    feature3: "90-day cookie duration with permanent tracking",
    feature4: "Comprehensive marketing tools and materials",
    feature5: "Dedicated affiliate manager support",
    feature6: "Global market reach with multi-language support",
    
    // Traffic chart
    trafficTrends: "Traffic Trends",
    last30Days: "Last 30 Days",
    last3Months: "Last 3 Months",
    last6Months: "Last 6 Months",
    lastYear: "Last Year",
    
    // Performance metrics
    performanceMetrics: "Affiliate Performance Metrics",
    industryAverageData: "Industry average data",
    conversionRate: "Conversion Rate",
    conversionCompare: "+1.2% vs Industry Avg",
    avgEarningsPerClick: "Avg. Earnings Per Click",
    avgEarningsCompare: "+$0.73 vs Industry Avg",
    avgOrderValue: "Avg. Order Value",
    avgOrderCompare: "+$210 vs Industry Avg",
    customerLifetimeValue: "Customer Lifetime Value",
    customerCompare: "+$850 vs Industry Avg",
    
    // Social listening
    socialListening: "Social Listening",
    lastUpdated: "Last updated: 8 hours ago",
    youtube: "YouTube",
    tiktok: "TikTok",
    twitter: "X (Twitter)",
    reddit: "Reddit",
    searchContent: "Search content...",
    mostRecent: "Most Recent",
    mostPopular: "Most Popular",
    highestEngagement: "Highest Engagement",
    positiveSentiment: "Positive Sentiment",
    youtubeTitle1: "Binance Tutorial 2023: Complete Beginner's Guide to Trading Cryptocurrency",
    byCreator: "By",
    daysAgo: "3 days ago",
    veryPositive: "Very Positive",
    watch: "Watch",
    save: "Save",
    viewMore: "View More",
    
    // Trending topics
    trendingTopics: "Trending Topics",
    tags: "Tags",
    wordCloud: "Word Cloud",
    timeline: "Timeline",
    bubbleChart: "Bubble Chart",
    heatMap: "Heat Map",
    extremeGrowth: "Extreme Growth (>80%)",
    
    // User reviews
    userReviews: "User Reviews",
    viewAllReviews: "View all 243 reviews",
    basedOnReviews: "based on 243 reviews",
    writeReview: "Write a Review",
    
    // Login modal
    loginRequired: "Login Required",
    loginModalMessage: "You need to log in or create an account to view additional content.",
    login: "Login",
    createAccount: "Create Account",
    
    // Demo toggle
    demoToggle: "Demo:",
    guest: "Guest",
    loggedIn: "Logged In"
  },
  
  // Vietnamese translations
  vi: {
    // General UI elements
    backButton: "Quay lại Danh sách",
    programName: "Chương trình Tiếp thị Liên kết Binance",
    category: "Sàn Giao dịch Tiền điện tử",
    joinButton: "Tham gia Chương trình",
    saveButton: "Lưu",
    shareButton: "Chia sẻ",
    description: "Chương trình Tiếp thị Liên kết của Binance cho phép bạn kiếm được hoa hồng lên đến 50% từ phí giao dịch của người dùng bạn giới thiệu. Với tư cách là sàn giao dịch tiền điện tử lớn nhất thế giới theo khối lượng, Binance cung cấp nền tảng đáng tin cậy với các công cụ tiếp thị toàn diện và thanh toán đúng hạn.",
    
    // Statistics and metrics
    commissionRate: "Tỷ lệ Hoa hồng",
    commissionDetail: "Hoa hồng trọn đời từ phí giao dịch",
    cookieDuration: "Thời hạn Cookie",
    cookieDetail: "Kèm theo theo dõi vĩnh viễn cho người dùng đã đăng ký",
    monthlyTraffic: "Lưu lượng Hàng tháng",
    trafficDetail: "Người truy cập toàn cầu (30 ngày qua)",
    paymentFrequency: "Tần suất Thanh toán",
    paymentValue: "Hàng ngày đến Hàng tháng",
    paymentDetail: "Lịch thanh toán tùy chỉnh",
    
    // Program details
    programDetails: "Chi tiết Chương trình",
    detailsContent1: "Chương trình Tiếp thị Liên kết Binance cung cấp một trong những cấu trúc hoa hồng cạnh tranh nhất trong ngành. Các đối tác liên kết có thể kiếm được lên đến 50% phí giao dịch từ người dùng được giới thiệu. Thu nhập được tính dựa trên khối lượng giao dịch của người được giới thiệu và có sẵn thông qua lịch thanh toán tùy chỉnh.",
    detailsContent2: "Binance cung cấp các quản lý tài khoản chuyên dụng để giúp tối ưu hóa chiến dịch và tối đa hóa chuyển đổi. Nền tảng cung cấp báo cáo thời gian thực, phân tích chi tiết và bộ tài liệu tiếp thị toàn diện để hỗ trợ nỗ lực quảng bá của bạn.",
    keyFeatures: "Tính năng Chính",
    feature1: "Hoa hồng lên đến 50% từ phí giao dịch",
    feature2: "Báo cáo và phân tích thời gian thực",
    feature3: "Thời hạn cookie 90 ngày với theo dõi vĩnh viễn",
    feature4: "Công cụ và tài liệu tiếp thị toàn diện",
    feature5: "Hỗ trợ quản lý đối tác chuyên dụng",
    feature6: "Phạm vi tiếp cận thị trường toàn cầu với hỗ trợ đa ngôn ngữ",
    
    // Traffic chart
    trafficTrends: "Xu hướng Lưu lượng",
    last30Days: "30 Ngày qua",
    last3Months: "3 Tháng qua",
    last6Months: "6 Tháng qua",
    lastYear: "Năm qua",
    
    // Performance metrics
    performanceMetrics: "Chỉ số Hiệu suất Tiếp thị Liên kết",
    industryAverageData: "Dữ liệu trung bình ngành",
    conversionRate: "Tỷ lệ Chuyển đổi",
    conversionCompare: "+1.2% so với Trung bình Ngành",
    avgEarningsPerClick: "Thu nhập Trung bình/Click",
    avgEarningsCompare: "+$0.73 so với Trung bình Ngành",
    avgOrderValue: "Giá trị Đơn hàng Trung bình",
    avgOrderCompare: "+$210 so với Trung bình Ngành",
    customerLifetimeValue: "Giá trị Vòng đời Khách hàng",
    customerCompare: "+$850 so với Trung bình Ngành",
    
    // Social listening
    socialListening: "Theo dõi Mạng xã hội",
    lastUpdated: "Cập nhật lần cuối: 8 giờ trước",
    youtube: "YouTube",
    tiktok: "TikTok",
    twitter: "X (Twitter)",
    reddit: "Reddit",
    searchContent: "Tìm kiếm nội dung...",
    mostRecent: "Gần đây nhất",
    mostPopular: "Phổ biến nhất",
    highestEngagement: "Tương tác cao nhất",
    positiveSentiment: "Cảm xúc tích cực",
    youtubeTitle1: "Hướng dẫn Binance 2023: Cẩm nang Giao dịch Tiền điện tử cho Người mới bắt đầu",
    byCreator: "Bởi",
    daysAgo: "3 ngày trước",
    veryPositive: "Rất Tích cực",
    watch: "Xem",
    save: "Lưu",
    viewMore: "Xem thêm",
    
    // Trending topics
    trendingTopics: "Chủ đề Thịnh hành",
    tags: "Thẻ",
    wordCloud: "Đám mây Từ",
    timeline: "Dòng thời gian",
    bubbleChart: "Biểu đồ Bong bóng",
    heatMap: "Bản đồ Nhiệt",
    extremeGrowth: "Tăng trưởng Cực cao (>80%)",
    
    // User reviews
    userReviews: "Đánh giá Người dùng",
    viewAllReviews: "Xem tất cả 243 đánh giá",
    basedOnReviews: "dựa trên 243 đánh giá",
    writeReview: "Viết Đánh giá",
    
    // Login modal
    loginRequired: "Yêu cầu Đăng nhập",
    loginModalMessage: "Bạn cần đăng nhập hoặc tạo tài khoản để xem nội dung bổ sung.",
    login: "Đăng nhập",
    createAccount: "Tạo Tài khoản",
    
    // Demo toggle
    demoToggle: "Demo:",
    guest: "Khách",
    loggedIn: "Đã đăng nhập"
  }
};

// Save the current language
let currentLanguage = document.documentElement.getAttribute('data-lang') || 'en';

/**
 * Apply translations to the page based on selected language
 * @param {string} lang - Language code ('en' or 'vi')
 */
function applyTranslations(lang) {
  if (!translations[lang]) {
    console.error(`Unsupported language: ${lang}`);
    return;
  }
  
  // Update html lang attribute
  document.documentElement.setAttribute('lang', lang);
  document.documentElement.setAttribute('data-lang', lang);
  
  // Update all elements with data-i18n attribute
  document.querySelectorAll('[data-i18n]').forEach(element => {
    const key = element.getAttribute('data-i18n');
    if (translations[lang][key]) {
      element.textContent = translations[lang][key];
    }
  });
  
  // Update all input placeholders with data-i18n-placeholder attribute
  document.querySelectorAll('[data-i18n-placeholder]').forEach(element => {
    const key = element.getAttribute('data-i18n-placeholder');
    if (translations[lang][key]) {
      element.setAttribute('placeholder', translations[lang][key]);
    }
  });
  
  // Update currentLanguage
  currentLanguage = lang;
  
  // Save language preference to localStorage
  localStorage.setItem('preferredLanguage', lang);
}

/**
 * Initialize language switcher
 */
function initializeLanguageSwitcher() {
  // Get language select element
  const languageSelect = document.getElementById('languageSelect');
  if (!languageSelect) return;
  
  // Get saved language preference from localStorage (if exists)
  const savedLanguage = localStorage.getItem('preferredLanguage');
  if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'vi')) {
    languageSelect.value = savedLanguage;
    applyTranslations(savedLanguage);
  }
  
  // Add change event listener
  languageSelect.addEventListener('change', function() {
    applyTranslations(this.value);
  });
}

// Initialize language switcher when DOM is loaded
document.addEventListener('DOMContentLoaded', initializeLanguageSwitcher); 